name: テンプレート
description: 基本的にこのテンプレートに沿ってIssueを作成。
title: ""
labels: ["enhancement", "new feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to raise a question
  - type: input
    id: task-name
    attributes:
      label: Task name
  - type: textarea
    id: what-happened
    attributes:
      label: Describe your feature request here
      placeholder: Put your question here.
      description: Please try to provide as much details as possible
      value: |
        - [ ] タスク1
        - [ ] タスク2
          - [ ] タスク2-1
    validations:
      required: true
  - type: checkboxes
  id: 確認
  attributes:
    label: チェック
    description: チェックします
    options:
      - label: labelの設定をしましたか？
      - label: Projectの
      - label: Linux
