name: テンプレート
description: 基本的にこのテンプレートに沿ってIssueを作成。
labels: ["enhancement", "new feature"]
body:
  - type: markdown
    attributes:
      value: |
        Labelの設定
        Projectの設定
        をしてください。
  - type: textarea
    id: overview
    attributes:
      label: 概要
      placeholder: 例)
      description: 概要を入力
      value: |
        - [ ] タスク1
        - [ ] タスク2
          - [ ] タスク2-1
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: 目的
      placeholder: 例)
      description: 目的を入力
      value: |
        - [ ] タスク1
        - [ ] タスク2
          - [ ] タスク2-1
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: タスク
      placeholder: 例)
      description: タスクを入力
      value: |
        - [ ] タスク1
        - [ ] タスク2
          - [ ] タスク2-1
