name: テンプレート
description: 基本的にこのテンプレートに沿ってIssueを作成。
labels: ["enhancement", "new feature"]
body:
  - type: markdown
    attributes:
      value: |
        以下の項目を確認してからIssueを送信してください。
        
        * Labelsの設定
        * Projectsの設定
        * Issue作成後にProjectsのStatusを設定
        
  - type: textarea
    id: overview
    attributes:
      label: 概要
      placeholder: 例)
      description: 概要を入力
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: 目的
      placeholder: 例)
      description: 目的を入力
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: タスク
      description: タスクを入力
      value: |
        - [ ] タスク1
        - [ ] タスク2
          - [ ] タスク2-1
